src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="user")
     */
    private $task;

    public function __construct()
    {
        $this->task = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */

    public function __toString(){
        return $this->getTask();
    }
    
    public function getTask(): Collection
    {
        return $this->task;
    }

    public function addTask(Task $task): self
    {
        if (!$this->task->contains($task)) {
            $this->task[] = $task;
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->task->contains($task)) {
            $this->task->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class HomePageController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     */
    public function index(Request $request)
    {
        $pdo = $this->getDoctrine()->getManager();

        $user = new User();
        $formUser = $this->createForm(UserType::class, $user);

        $formUser->handleRequest($request);
        if ( $formUser->isSubmitted() && $formUser->isValid() ) {
            
            $user->setCreatedAt(new\ DateTime('now')); // date d'incription
            
            $pdo->persist($user);
            $pdo->flush();

            $this->addFlash("success", "Utilisateur ajouté !");
        }

        $users = $pdo->getRepository(User::class)->findAll();

        return $this->render('home_page/index.html.twig', [
            'users' => $users,
            'form_user_add' => $formUser->createView()
        ]);
    }


    /**
     * PAGE UTILISATEUR 
     * @Route("/{id}", name="my_user")
     */

     public function user(Request $request, User $user=null){

        if ($user !=null) {
            //si l'utilisateur existe
            
            $formUser = $this->createForm(UserType::class, $user);
            $formUser->handleRequest($request);

            if ( $formUser->isSubmitted() && $formUser->isValid() ) {

                $pdo = $this->getDoctrine()->getManager();
                $pdo->persist($user);
                $pdo->flush();

                $this->addFlash("success", "Utilisateur modifié !");
            }

            return $this->render('home_page/user.html.twig', [
                'user' => $user,
                'form_user_edit' => $formUser->createView()
            ]);
        }
        else {
            // l'utilisateur n'existe pas 
            $this->addFlash("danger", "Utilisateur introuvable ");
            return $this-> redirectToRoute('home');
        }
     }

     /**
     * PAGE SUPRESSION
     * @Route("/user/delete/{id}", name="delete_user")
     */

    public function deleteUser(User $user=null) {
        if($user != null) {
            $pdo = $this->getDoctrine()->getManager();
            $pdo->remove($user); 
            $pdo->flush();
        }

        return $this->redirectToRoute('home');
    }


}

templates/home_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HomePage{% endblock %}

{% block body %}
    <h1>Utilisateurs</h1>

    <a href="{{path('task')}}">Voir les taches</a>

    {% if users is not empty %}
        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Tâches</th>
                    <th>Date d'inscription</th>
                    <th>Action</th>

                </tr>
            </thead>

            <tbody>
                {% for user in users %}
                
                <tr>
                    <td>
                        <a href="{{path('my_user', {'id': user.id})}}">
                            {{ user.lastname }} {{ user.firstname }}
                        </a>
                    </td>
                    <td> {{ user.task}} </td>
                    <td> {{ user.email}} </td>
                    <td> </td>
                    <td> {{ user.createdAt|date('d/m/y')}} </td>

                    <td>
                        <a href="{{ path('delete_user', {'id': user.id})}}">
                        X </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>

        </table>
            
        {% else %}
            <p>Il n'y a aucun utilisateur</p>
        {% endif %}
        
        <h2>Ajouter un utilisateur</h2>
        {{ form(form_user_add)}}


{% endblock %}

templates/home_page/user.html.twig
{% extends  "base.html.twig" %}

{% block title %} {{ user.lastname }} {{ user.firstname }} {% endblock %}

{% block body %}
    <h1>{{ user.lastname }} {{ user.firstname }} </h1>
    <h3>email: {{ user.email }}</h3>
    <h3>date d'inscription : {{ user.createdAt|date('d/m/y')}}</h3>
    <br/>

     <h2>Modifier</h2>
    {{form(form_user_edit)}}


    {% if user.task is not empty %}
        <h3>Tâche attribué :</h3>

        {% for task in user.task %}

        <p> {{ task.name }} </p>
        <p>{{ task.state ? 'Validée' : 'En cours' }}</p>
        <p>
            <a href="{{ path('delete_task', {'id': task.id})}}">
             Supprimer cette tâche</a>
        </p>
        {% endfor %}

    {% else %}
        <p>Aucune tâche n'est attribué à {{ user.lastname }} {{ user.firstname }} </p>
    {% endif %}

    </br>
    <a href="{{path('home')}}">Retour aux Utilisateurs</a>

{% endblock %}